# ----------- Build Stage -------------
FROM maven:3.9.0-eclipse-temurin-17 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# ----------- Runtime Stage ----------
FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /app/target/KeelungSights.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]